modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="power"
version="2.0.3"
displayName="Keepers of the Stones"
credits="Created by ModdingCommonwealth"
displayURL="https://www.curseforge.com/minecraft/mc-mods/keepers-of-the-stones"
updateJSONURL="https://raw.githubusercontent.com/ModdingCommonwealth/Keepers-of-the-Stones/main/kos.json"
logoFile="logo.png"
authors="ModdingCommonwealth"
description='''
This mod will add new sources of energy to the world with which you can transform into masters of the elements.
'''

[[dependencies.power]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




