modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="power"
version="2.3.2"
displayName="Keepers of the Stones"
credits="Created by MagicalAlexey, with the support of Chiffon Medal, FixEnd, 7ZLBeka, Superlexaan as well as many other contributors."
displayURL="https://github.com/Hexagon-Studio/Keepers-of-the-Stones/wiki"
updateJSONURL="https://raw.githubusercontent.com/MagicalAlexey/Keepers-of-the-Stones/main/kos.json"
logoFile="logo.png"
authors="Hexagon Studio"
description='''
This mod will add new sources of energy to the world with which you can transform into masters of the elements.
'''

[[dependencies.power]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




