name: New feature
description: Suggest a new feature (search for duplicates first)
labels: new feature
body:
 - type: textarea
   attributes:
    label: Feature description
    description: Tell us what your idea is
    placeholder: Tell us here about your idea
   validations:
    required: true
 - type: textarea
   attributes:
    label: Concepts
    description: Attach concepts ideas.
    placeholder: Attach concepts ideas.
   validations:
    required: false